import assert from 'node:assert/strict';
import { PokerPresentation } from '../src/components/poker/motion/presentation';
import { ChipTimeline } from '../src/components/poker/chips/chipModel';
import type { PokerGameState } from '../src/types/poker';
const start = { mode: 'offline', stage: 'preflop', visualEpoch: 1, players: Array.from({length: 3}, (_, i) => ({ id: String(i), name: `P${i}`, chips: 100, currentBet: 0, totalMatchInvested: 0, folded: false, isAllIn: false, holeCards: [{ id: `a${i}`, rank: 14-i, suit: 'hearts' }, { id: `b${i}`, rank: 10-i, suit: 'clubs' }] })), communityCards: [], winnerIds: [] } as unknown as PokerGameState;
const model = new PokerPresentation();
model.sync(start, 100);
assert.equal(model.view(100).cue?.label, 'READY?');
assert.equal(model.view(350).cue?.label, 'GAME START!');
const first = {...start, players: start.players.map((p,i) => i===0 ? {...p,isAllIn:true,lastAction:'ALL IN',chips:0,totalMatchInvested:100} : p)};
model.sync(first, 1000);
assert.equal(model.view(1000).cue?.detail, 'P0');
const second = {...first,players:first.players.map((p,i)=>i===1?{...p,isAllIn:true,lastAction:'ALL IN',chips:0,totalMatchInvested:100}:p)};
model.sync(second, 1500);
assert.equal(model.view(1500).cue?.detail, 'P1');
model.sync({...second}, 1600);
assert.equal(model.cues.filter(c=>c.label==='ALL IN').length, 1, 'duplicate snapshots do not replay all-in');
const ended = {...second,stage:'ended',communityCards:[2,4,6,8,10].map(rank=>({id:`c${rank}`,rank,suit:'spades'})),chipAwards:[{playerId:'0',amount:200,potIndex:0,kind:'win'}],winnerIds:['0']} as PokerGameState;
model.sync(ended, 2000);
assert.ok(model.payoutAt > 2800, 'payout waits for runout and hole-card reveals');
assert.equal(model.view(2000).revealedPlayers.size,0);
assert.equal(model.view(model.payoutAt).revealedPlayers.size,3);
assert.ok(model.view(model.payoutAt).winnerReady);
assert.equal(model.view(2100).resultReady,false);
const due = model.payoutAt;
model.sync({...ended}, 2200);
assert.equal(model.payoutAt,due,'repeated final snapshots retain the original schedule');
const money = new ChipTimeline();
money.sync({hand:'h',version:1,pot:200,ended:false,players:[{id:'0',chips:0,invested:100}],pots:[200]},0);
money.sync({hand:'h',version:2,pot:200,ended:true,players:[{id:'0',chips:200,invested:100}],pots:[200],awards:ended.chipAwards,payoutNotBefore:due},2000);
assert.ok(money.flights[0].start>=due);
assert.equal(money.view(2200).balances['0'],0);
assert.equal(money.view(2200).pots[0],200);
model.sync({...start,visualEpoch:2},5000);
assert.equal(model.view(5000).revealedPlayers.size,0);
assert.equal(model.payoutAt,0,'next hand cancels old sequence');
model.sync(ended,6000,true);
assert.equal(model.view(6000).cue,null);
assert.equal(model.view(6000).resultReady,true);
assert.equal(model.view(6000).revealedPlayers.size,3);
const recovered = new PokerPresentation();
recovered.sync(ended,100);
assert.equal(recovered.payoutAt,0,'opening a historical result does not replay the hand');
const fold = new PokerPresentation(); fold.sync(start,100);
fold.sync({...ended,communityCards:[],players:ended.players.map((p,i)=>({...p,folded:i>0}))},200);
assert.equal(fold.cues.some(c=>c.label==='SHOWDOWN'),false,'uncontested pots do not invent a showdown');
console.log('PASS motion: first deal, multiple all-ins, duplicates, direct-ended showdown, payout ordering, recovery, reduced motion and fold win');
