import assert from 'node:assert/strict';
import type { Response } from 'express';
import { MAX_SSE_BUFFER_BYTES, sendSerializedSse } from '../server/sseTransport';
const metrics = {framesSent: 0, framesDeduplicated: 0, payloadBytesSent: 0, heartbeatsSent: 0, slowConnectionsClosed: 0};
const client = () => ({writableEnded: false, destroyed: false, writableLength: 0, chunks: [] as string[], write(chunk: string) {this.chunks.push(chunk); return true;}, destroy() {this.destroyed = true;}});
const a=client(), b=client();
const send=(response: ReturnType<typeof client>, event: string, data: string, dedupe=true)=>sendSerializedSse(response as unknown as Response,event,data,metrics,dedupe);
assert.equal(send(a,'match-state','{"seat":"a"}'),true);
assert.equal(a.chunks[0],'event: match-state\ndata: {"seat":"a"}\n\n');
assert.equal(send(a,'match-state','{"seat":"a"}'),false);
assert.equal(send(b,'match-state','{"seat":"b"}'),true,'dedupe must be per response, never across player perspectives');
assert.equal(send(a,'match-state','{"seat":"a","v":2}'),true);
assert.equal(send(a,'heartbeat','{}',false),true);
assert.equal(send(a,'heartbeat','{}',false),true);
a.writableLength=MAX_SSE_BUFFER_BYTES+1;
assert.equal(send(a,'match-state','{"v":3}'),false);
assert.equal(a.destroyed,true);
assert.equal(metrics.slowConnectionsClosed,1);
assert.equal(send(a,'match-state','{"v":4}'),false);
assert.equal(send(b,'match-state','{"seat":"b","v":3}'),true,'slow subscriber must not block others');
assert.equal(metrics.framesDeduplicated,1);
assert.equal(metrics.heartbeatsSent,2);
console.log('SSE framing, dedupe, isolation and bounded slow-client buffer checks passed.');
